apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: naskio/strapi
        ports:
        - containerPort: 1337
        env:
        - name: DATABASE_CLIENT
          value: postgres
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: 5432
        - name: DATABASE_NAME
          value: postgresdb
        - name: DATABASE_USERNAME
          value: admin
        - name: DATABASE_PASSWORD
          value: test123
        - name: DATABASE_SSL
          value: false